title: Anjeli Taruc
description: 

url: https://anjeli-jac.github.io/portfolio/
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: Anjeli-Jac
    email: anjelitaruc02@gmail.com
    linkedin: anjeli-mae-taruc-2b4762290

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
